apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-1gb
spec:
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: aws-ebs
  hostPath:
    path: /tmp

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-hostpath-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: aws-ebs
  resources:
    requests:
      storage: 512Mi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
reclaimPolicy: Delete
allowVolumeExpansion: false
mountOptions:
  - debug
volumeBindingMode: Immediate